services:
  - type: web
    name: employee-salary-management-frontend
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_URL
        value: https://employee-salary-management-incubyte.onrender.com
